#!/usr/bin/env bash

source ./.env
export $(cut -d= -f1 ./.env)

if [[ "yes" == "$RECLONE" ]]; then
    #prepare data
    rm -rf $MAGENTO_PATH
    mkdir -p $MAGENTO_PATH
    cd $MAGENTO_PATH
    #chown -R $USER:wheel .
    chmod g+s .

	git clone --depth 1 git@github.com:${GIT_REPO_CE}/$MAGENTO_CE_DIR.git -b ${GIT_BRANCH_CE}

	if [[ "EE" == "$MAGENTO_EDITION" ]] || [[ "B2B" == "$MAGENTO_EDITION" ]]; then
        git clone --depth 1 git@github.com:${GIT_REPO_EE}/$MAGENTO_EE_DIR.git -b ${GIT_BRANCH_EE}
	fi

	if [[ "B2B" == "$MAGENTO_EDITION" ]]; then
        git clone --depth 1 git@github.com:${GIT_REPO_B2B}/magento2b2b.git -b ${GIT_BRANCH_B2B}
        cp magento2ee/dev/tools/build-ee.php magento2b2b/dev/tools/build-ee.php
	fi

	if [[ "yes" == "$MSI_INSTALL" ]]; then
        git clone --depth 1 git@github.com:${GIT_REPO_MSI}/inventory.git -b ${GIT_BRANCH_MSI}
        mkdir -p inventory/dev/tools
        cp magento2ee/dev/tools/build-ee.php inventory/dev/tools/build-ee.php
    fi

    if [[ "yes" == "$STOREFRONT_INSTALL" ]]; then
        git clone --depth 1 git@github.com:${GIT_REPO_CATALOG_SF}/catalog-storefront.git -b ${GIT_BRANCH_CATALOG_SF}
        mkdir -p catalog-storefront/dev/tools
        cp magento2ee/dev/tools/build-ee.php catalog-storefront/dev/tools/build-ee.php

	    git clone --depth 1 git@github.com:${GIT_REPO_CATALOG_SF_EE}/catalog-storefront-ee.git -b ${GIT_BRANCH_CATALOG_SF_EE}
        mkdir -p catalog-storefront-ee/dev/tools
        cp magento2ee/dev/tools/build-ee.php catalog-storefront-ee/dev/tools/build-ee.php

        git clone --depth 1 git@github.com:${GIT_REPO_SAAS_EXPORT}/saas-export.git -b ${GIT_BRANCH_SAAS_EXPORT}
        mkdir -p saas-export/dev/tools
        cp magento2ee/dev/tools/build-ee.php saas-export/dev/tools/build-ee.php

	    git clone --depth 1 git@github.com:${GIT_REPO_DSSI}/data-solutions-services-id.git -b ${GIT_BRANCH_DSSI}
	    mkdir -p data-solutions-services-id/dev/tools
	    cp magento2ee/dev/tools/build-ee.php data-solutions-services-id/dev/tools/build-ee.php
	fi
fi
