#!/usr/bin/env bash

set -ex

source ./.env
export $(cut -s -d= -f1 ./.env)
DOCKER_PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


 if [[ ! -f ./etc/php/auth.json ]] ; then
   echo 'auth.json nothing found. Please, add ./etc/php/auth.json'
   exit
 fi

# for Mutagen installation: Update Magento path in mutagen.yml
sed -ie "s|alpha: .*|alpha: \"$MAGENTO_PATH\"|" $DOCKER_PROJECT_DIR/mutagen.yml

# Add domain to hosts
#sudo -- sh -c "echo '127.0.0.1 $MAGENTO_DOMAIN' >> /etc/hosts"

if [[ "" != "$GIT_CLONE_DEPTH" ]]; then
  GIT_CLONE_DEPTH="--depth=${GIT_CLONE_DEPTH}"
fi

if [[ "yes" == "$RECLONE" ]]; then
  cd $MAGENTO_PATH
  for edition in $INSTALLED_REPOS; do

   if [[ -d ./${edition} ]] || [[ -d "./magento2ce/${edition}" ]]; then
#       repo exists, do nothing
      continue
   fi

     repo=$(echo "GIT_REPO_${edition}" | sed "s|-|_|g")
     branch=$(echo "GIT_BRANCH_${edition}" | sed "s|-|_|g")
     path=$edition

     chmod g+s .
     git clone ${GIT_CLONE_DEPTH} git@github.com:${!repo}.git ${path} -b ${!branch}
  done
else
 cd $MAGENTO_PATH/magento2ce
 export GIT_DISCOVERY_ACROSS_FILESYSTEM=1 && git checkout -- .
fi

# workaround to work with magento/magento2 && magento/partners-magento2ee repos
cd $MAGENTO_PATH

echo 'project initialized'
