#!/usr/bin/env bash

set -ex

source ./.env
export $(cut -d= -f1 ./.env)
DOCKER_PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Add domain to hosts
#sudo -- sh -c "echo '127.0.0.1 $MAGENTO_DOMAIN' >> /etc/hosts"


if [[ "yes" == "$RECLONE" ]]; then
    #prepare data
    rm -rf $MAGENTO_PATH/storefront-search
    cd $MAGENTO_PATH
    #chown -R $USER:wheel .
    chmod g+s .

	git clone git@github.com:${GIT_REPO_storefront_search}.git storefront-search -b ${GIT_BRANCH_storefront_search}

else
 cd $MAGENTO_PATH/storefront-search
 export GIT_DISCOVERY_ACROSS_FILESYSTEM=1 && git checkout -- .
fi

cd $DOCKER_PROJECT_DIR
docker-compose up --build -d app-search
docker-compose exec app-search magento app_search_init
docker-compose exec app-search magento grpc_sf_search
