#!/usr/bin/env bash

source /var/www/magento-docker/.env
export $(cut -d= -f1 /var/www/magento-docker/.env)

bin/magento config:set web/seo/use_rewrites 1
bin/magento config:set dev/template/allow_symlink 1
bin/magento config:set admin/security/admin_account_sharing 1
bin/magento config:set admin/security/session_lifetime 31536000
bin/magento config:set system/media_storage_configuration/media_database default_setup
bin/magento config:set catalog/search/engine elasticsearch${ELASTICSEARCH_VERSION}
bin/magento config:set catalog/search/elasticsearch${ELASTICSEARCH_VERSION}_server_hostname elastic
bin/magento setup:config:set -n --session-save=redis --session-save-redis-host=redis --cache-backend-redis-db=0
bin/magento setup:config:set -n --cache-backend=redis --cache-backend-redis-server=redis --cache-backend-redis-db=1
bin/magento setup:config:set -n --amqp-host=rabbit --amqp-user=guest --amqp-password=guest
