#!/usr/bin/env bash

bin/magento config:set web/seo/use_rewrites 1
bin/magento config:set dev/template/allow_symlink 1
bin/magento config:set admin/security/admin_account_sharing 1
bin/magento config:set admin/security/session_lifetime 31536000
