#!/usr/bin/env bash

#Download gRPC server
if [ ! -f /usr/bin/rr-grpc ]; then
    curl -LJO https://github.com/spiral/php-grpc/releases/download/v1.4.0/rr-grpc-1.4.0-linux-amd64.tar.gz
    tar -xzf rr-grpc-1.4.0-linux-amd64.tar.gz
    cp rr-grpc-1.4.0-linux-amd64/rr-grpc /usr/bin
    rm -rf rr-grpc-1.4.0-linux-amd64 rr-grpc-1.4.0-linux-amd64.tar.gz
fi
echo 'gRPC server installed'

echo 'Start gRPC initialization...'
bin/magento storefront:grpc:init \\Magento\\CatalogStorefrontApi\\Api\\CatalogProxyServer
echo 'End of gRPC initialization'

echo 'Starting gRPC server...';
# Run gRPC server
./vendor/bin/grpc-server
echo 'gRPC server started';
