#!/usr/bin/env bash

source /var/www/magento-docker/.env
export $(cut -d= -f1 /var/www/magento-docker/.env)

if [ -f magento.proto ] && [ -h magento.proto ]; then
  echo 'magento.proto must be not a link. Copying from catalog-storefront'
  unlink magento.proto
  cp /var/www/catalog-storefront/magento.proto .
fi

echo 'Start gRPC initialization...'
bin/magento storefront:grpc:init ${GRPC_SERVICE_CLASS}
echo 'End of gRPC initialization'

echo 'Starting gRPC server...';
# Run gRPC server
nohup bash -c "./vendor/bin/grpc-server&"
echo 'gRPC server started';
