#!/bin/bash
#https://github.com/clawrock/magento2-debug

! composer show clawrock/magento2-debug >/dev/null 2>&1
isset=$?

if [[ ${isset} != 1 ]]; then
    composer require --dev clawrock/magento2-debug
    bin/magento setup:upgrade
fi

set +e
bin/magento config:show clawrock_debug/general/active >/dev/null 2>&1
enable=$?
set -e

bin/magento config:set clawrock_debug/general/active ${enable}