#!/bin/bash
shopt -s extglob

source /var/www/magento-docker/.env
export $(cut -d= -f1 /var/www/magento-docker/.env)

cp /var/www/magento-docker/etc/php/tools/* /usr/local/bin 2>/dev/null || :

#clean project dir
if [[ -d .git ]]; then
   git clean -dfx -e '.idea' $(mount | grep -oP '/var/www/magento2ce/\K\S*' | xargs -rn 1 echo '-e ')
   git checkout composer.lock composer.json
fi

# remove links
find  . -type l -delete

#apply edition
dst="/var/www/magento2ce"
for edition in "$@"; do
   if ! [[ -d ../${edition} ]]; then
      edition=magento2${edition}
   fi
   if [[ ${edition} == "data-solutions-services-id" ]]; then
      dst="/var/www/magento2ce/app/code/Magento"
   fi
   if [[ -d ../${edition} ]]; then
     if [[ ${edition} == "magento2ee" ]] || [[ ${edition} == "magento2b2b" ]]; then
       cp -rlf /var/www/${edition}/composer* ${dst} 2>/dev/null
       cp -rlf /var/www/${edition}/setup /var/www/magento2ce/setup 2>/dev/null
       cp -rf /var/www/${edition}/dev ${dst} 2>/dev/null
     fi
     if [[ ${edition} == *"storefront"* ]]; then
       set +ex;
       cp -rf /var/www/${edition}/dev ${dst} 2>/dev/null
       set -ex;
     fi
     if [[ ${edition} == *"saas-export"* ]]; then
       set +ex;
       cp -rf /var/www/${edition}/dev ${dst} 2>/dev/null
       set -ex;
     fi

     php /var/www/${edition}/dev/tools/build-ee.php -- --command unlink --exclude true --ce-source ${dst} --ee-source /var/www/${edition}
     php /var/www/${edition}/dev/tools/build-ee.php -- --command link --exclude true --ce-source ${dst} --ee-source /var/www/${edition}

   fi
done

#install magento
composer install

mysql -uroot -hdb -e "DROP DATABASE IF EXISTS db; create database db;"
rm -rf generated/* var/* app/etc/env.php app/etc/config.php

# echo y | bin/magento setup:uninstall
bin/magento setup:install \
   --cleanup-database \
   --backend-frontname=admin \
   --admin-lastname=Admin \
   --admin-firstname=Admin \
   --admin-email=magento@mailinator.com \
   --admin-user=admin \
   --admin-password=123123q \
   --db-name=magento \
   --db-host=db \
   --elasticsearch-host=elastic


 echo 'install module dependencies'
 php dev/tools/install-dependencies.php .
#do x-setup lines
#IFS=$'\n' setup=($(yq read /var/www/magento-docker/docker-compose.yml services.*.x-setup | grep -oP '^(?:\s*\-\s)+(?!null)\K.*'))
#for i in ${setup[*]}; do eval "${i}"; done
