#!/bin/bash
shopt -s extglob

source /tmp/.env
#cp /var/www/magento-docker/etc/php/tools/* /usr/local/sbin

#clean project dir
if [[ -d .git ]]; then
   git clean -dfx -e '.idea' $(mount | grep -oP '/var/www/magento2ce/\K\S*' | xargs -rn 1 echo '-e ')
   git checkout composer.lock composer.json
fi

rm -rf generated/* var/* app/etc/env.php

# remove links
find  . -type l -delete

cp -r /tmp/build.php /var/www/magento2ce/dev/tools/build.php
# build.php is a copy /var/www/magento2ee/dev/tools/build-ee.php
php /var/www/magento2ce/dev/tools/build.php --command unlink

repos=$INSTALLED_REPOS
if [[ ${MAGENTO_EDITION} == 'EE' ]]; then
  repos=${INSTALLED_REPOS_EE}
fi
if [[ ${MAGENTO_EDITION} == 'B2B' ]]; then
  repos=${INSTALLED_REPOS_B2B}
fi

echo "$(date +"%T") Magento ${MAGENTO_EDITION} Installation START"

for edition in $repos; do
  echo "Applying $edition edition"

  #apply edition
  dst="/var/www/magento2ce"
  #if ! [[ -d ../${edition} ]]; then
  #  edition=magento2${edition}
  #fi
  if [[ ${edition} == "magento2ce" ]]; then
      continue;
   fi
   if [[ ! ${edition} == "magento2ce" ]] &&
      [[ ! ${edition} == "magento2ee" ]] &&
      [[ ! ${edition} == "magento2b2b" ]] &&
      [[ ! ${edition} == "magento2-sample-data" ]] &&
      [[ ! ${edition} == "magento2-sample-data-ee" ]];
       then
      dst="/var/www/magento2ce/app/code/Magento"
   fi

   if [[ -d ../${edition} ]]; then
     php /var/www/magento2ce/dev/tools/build.php --command link --exclude true --ce-source ${dst} --ee-source /var/www/${edition}
     if [[ ${edition} == "magento2ee" ]] || [[ ${edition} == "magento2b2b" ]]; then
       if [[ ${edition} == "magento2ee" ]]; then
        cp -rlf /var/www/${edition}/composer* ${dst} 2>/dev/null
       fi
       cp -rlf /var/www/${edition}/setup /var/www/magento2ce/setup 2>/dev/null
     fi
     set +ex;
     cp -rf /var/www/${edition}/dev ${dst} 2>/dev/null
     set -ex;
   else
      echo "!!!!!!!!!!!!"
      echo "ERROR: Directory for '${edition}' edition doesn't exist"
      echo "!!!!!!!!!!!!"
      exit
   fi
done

# Install live-search graphql dependency
composer require gmostafa/php-graphql-client
# Install live-search firebase/php-jwt dependency
composer require firebase/php-jwt

#install magento
composer install
echo y | bin/magento setup:uninstall
bin/magento setup:install \
   --cleanup-database \
   --backend-frontname=admin \
   --admin-lastname=Admin \
   --admin-firstname=Admin \
   --admin-email=magento@mailinator.com \
   --base-url=https://${MAGENTO_DOMAIN}/ \
   --admin-user=${ADMIN_USER} \
   --admin-password=${ADMIN_PASSWORD} \
   --db-name=magento \
   --db-host=db \
   --elasticsearch-host=elastic \
   --db-prefix=

#bin/magento module:disable Magento_TwoFactorAuth

bin/magento module:enable --all

if [[ "$INSTALL_LIVESEARCH" == 'yes' ]]; then
  if [[ "$MAGENTO_EDITION" == 'CE' ]]; then
    bin/magento module:disable Magento_Elasticsearch Magento_Elasticsearch6 Magento_Elasticsearch7 Magento_AdvancedSearch
  else
    bin/magento module:disable Magento_Elasticsearch Magento_Elasticsearch6 Magento_Elasticsearch7 Magento_ElasticsearchCatalogPermissions Magento_AdvancedSearch #Magento_InventoryElasticsearch
  fi
fi

# add QA environment to env.php, https://github.com/magento-commerce/magento-live-search#connecting-to-qa-environment
php -r '$sC = include "/tmp/livesearch-env.php"; $env = include "app/etc/env.php"; $env = array_replace_recursive($env, $sC); $contents = var_export($env, true); file_put_contents("app/etc/env.php", "<?php\n return $contents; \n");'

# add config, so search would use QA environment
cd '/var/www/'
php -r '$filesConfig = include "/tmp/livesearch-qa-config.php"; foreach ($filesConfig as $file => $config) { file_put_contents($file, strtr(file_get_contents($file), $config)); };'
cd '/var/www/magento2ce/'



echo "Compiling Magento with changes..."
bin/magento setup:upgrade
bin/magento setup:di:compile
bin/magento cache:flush

# apply Magento configs
php -f /tmp/magento_config_setup.php

#taken from config_setup
bin/magento config:set web/secure/base_url https://${MAGENTO_DOMAIN}/

echo "Magento 2 Successfully installed!"
echo "To open it navigate to $MAGENTO_DOMAIN"
echo "Ignore git apply errors if they occur."

echo "$(date +"%T") Magento ${MAGENTO_EDITION} Installation END"
git apply /tmp/path-validator.patch

#do x-setup lines
#IFS=$'\n' setup=($(yq read /var/www/magento-docker/docker-compose.yml services.*.x-setup | grep -oP '^(?:\s*\-\s)+(?!null)\K.*'))
#for i in ${setup[*]}; do eval "${i}"; done
