#!/bin/bash
shopt -s extglob

rm -rf app/etc/env.php app/etc/config.php

bash dev/tools/make_standalone_app.sh

composer global require hirak/prestissimo
composer install

bin/command storefront:pricing:init \
  --db-host=db --db-name=magento --db-user=root --db-password= --db-table-prefix=
