#!/bin/bash
shopt -s extglob

DB_HOST=db

# for mutagen installation:
# cp /var/www/magento-docker/etc/php/tools/* /usr/local/bin 2>/dev/null || :

#install magento

#composer global require hirak/prestissimo
composer install

#if [[ -f dev/tools/install-dependencies.php ]]; then
#  echo 'install module dependencies'
#  php dev/tools/install-dependencies.php .
#fi

mysql -uroot -h${DB_HOST} -e "DROP DATABASE IF EXISTS magento; create database magento;"
rm -rf generated/* var/* app/etc/env.php

# echo y | bin/magento setup:uninstall
bin/magento setup:install \
  --backend-frontname=admin \
  --admin-lastname=Admin \
  --admin-firstname=Admin \
  --admin-email=magento@mailinator.com \
  --admin-user=admin \
  --admin-password=123123q \
  --db-name=magento \
  --db-host=${DB_HOST} \
  --elasticsearch-host=elastic \
  --search-engine=elasticsearch${ELASTICSEARCH_VERSION} \
  --base-url=http://${MAGENTO_DOMAIN}/ \
  --session-save=redis \
  --session-save-redis-host=redis \
  --session-save-redis-db=0 \
  --cache-backend=redis \
  --cache-backend-redis-server=redis \
  --cache-backend-redis-db=1

bin/magento config:set web/secure/base_url http://${MAGENTO_DOMAIN}/

bin/magento -f setup:static-content:deploy
# bin/magento module:disable Magento_TwoFactorAuth
# rm -rf generated/
