#!/bin/bash
shopt -s extglob

DB_HOST=db
source /var/www/magento-docker/.env
export $(cut -s -d= -f1 /var/www/magento-docker/.env)

# for mutagen installation:
# cp /var/www/magento-docker/etc/php/tools/* /usr/local/bin 2>/dev/null || :

# remove links
find  . -type l -delete

#apply edition
dst="/var/www/magento2ce"

#clean project dir (not for mutagen)
if [[ -d .git ]]; then
   git clean -dfx -e '.idea' $(mount | grep -oP '/var/www/magento2ce/\K\S*' | xargs -rn 1 echo '-e ')
   git checkout composer.lock composer.json
fi

for edition in ${INSTALLED_REPOS}; do

   if [[ ${edition} == "magento2ce" ]] || [[ ${edition} == "graphql" ]] ||\
      [[ ${edition} == "storefront-message-broker" ]] || [[ ${edition} == "storefront-search-ce" ]] ||\
      [[ ${edition} == "storefront-pricing-ce" ]] || [[ ${edition} == "storefront-product-reviews-ce" ]] ||\
      [[ ${edition} == "catalog-storefront" ]]; then
      # skip copying, linking for standalone applications
      continue
   fi

   # copy into app/code/Magento
   if [[ ${edition} == "inventory" ]]; then
      dst="/var/www/magento2ce/app/code/Magento"
   else
      dst="/var/www/magento2ce"
   fi

   # copy into app/code/Magento
   if [[ ${edition} == "module-grpc" ]]; then
      mkdir -p /var/www/magento2ce/app/code/Magento/Grpc
      dst="/var/www/magento2ce/app/code/Magento/Grpc"
   else
      dst="/var/www/magento2ce"
   fi

   if [[ -d ../${edition} ]] || [[ -d ../magento2ce/${edition} ]]; then

     source=/var/www/${edition}

     if [ ${MUTAGEN_INSTALLATION} == "NO" ]; then
       cp -rlf ${source}/!(.git|vendor|..|.) ${dst}
     else
       if [[ ${edition} == "*magento2*" ]]; then
         cp -rlf /var/www/magento2ee/composer* ${dst} 2>/dev/null
       fi
       if [[ ${edition} == *"storefront"* ]]; then
         set +ex;
         cp -rf /var/www/${edition}/dev ${dst} 2>/dev/null
         set -ex;
       fi
       if [[ ${edition} == *"commerce-data-export"* ]]; then
         set +ex;
         cp -rf /var/www/${edition}/dev ${dst} 2>/dev/null
         set -ex;
       fi

       php /var/www/commerce-data-export/dev/tools/build-sc.php --command link --exclude true --ce-source ${dst} --ee-source ${source}
     fi
   fi
done

#install magento

composer install

if [[ -f ../catalog-storefront/dev/tools/install-dependencies.php ]] && [[ ! -f dev/tools/install-dependencies.php ]]; then
  cp ../catalog-storefront/dev/tools/install-dependencies.php dev/tools/install-dependencies.php
fi

if [[ -f dev/tools/install-dependencies.php ]]; then
  echo 'install module dependencies'
  php dev/tools/install-dependencies.php .
fi

mysql -uroot -h${DB_HOST} -e "DROP DATABASE IF EXISTS magento; create database magento;"
rm -rf generated/* var/* app/etc/env.php app/etc/config.php

# echo y | bin/magento setup:uninstall
bin/magento setup:install \
  --backend-frontname=admin \
  --admin-lastname=Admin \
  --admin-firstname=Admin \
  --admin-email=magento@mailinator.com \
  --admin-user=admin \
  --admin-password=123123q \
  --db-name=magento \
  --db-host=${DB_HOST} \
  --elasticsearch-host=elastic \
  --search-engine=elasticsearch${ELASTICSEARCH_VERSION} \
  --base-url=http://${MAGENTO_DOMAIN}/ \
  --session-save=redis \
  --session-save-redis-host=redis \
  --session-save-redis-db=0 \
  --cache-backend=redis \
  --cache-backend-redis-server=redis \
  --cache-backend-redis-db=1 \
  --amqp-host=rabbit \
  --amqp-user=guest \
  --amqp-password=guest

bin/magento config:set web/secure/base_url http://${MAGENTO_DOMAIN}/

#do x-setup lines
#IFS=$'\n' setup=($(yq read /var/www/magento-docker/docker-compose.yml services.*.x-setup | grep -oP '^(?:\s*\-\s)+(?!null)\K.*'))
#for i in ${setup[*]}; do eval "${i}"; done
