#!/bin/bash
shopt -s extglob

source /var/www/magento-docker/.env
export $(cut -s -d= -f1 /var/www/magento-docker/.env)

rm -rf app/etc/env.php app/etc/config.php

bash dev/tools/make_standalone_app.sh
composer install

bin/command storefront:pricing:init \
  --db-host=db --db-name=magento --db-user=root --db-password= --db-table-prefix=
