#!/bin/bash
shopt -s extglob

rm -rf app/etc/env.php app/etc/config.php

bash dev/tools/make_standalone_app.sh
composer config repositories.libraries path "/var/www/storefront-libraries/modules/*"
composer global require hirak/prestissimo
composer install

bin/command storefront:search:init \
  --magento-db-host=db --magento-db-name=magento --magento-db-user=root --magento-db-password= --magento-db-table-prefix=\
  --magento-es-engine=elasticsearch7 --magento-es-hostname=localhost --magento-es-index-prefix=magento2_search_

bin/command storefront:cache:setup --cache-backend redis
