#!/bin/bash

shopt -s extglob
#set -- ${1:-'ce'}

if [[ -d .git ]]; then
   git clean -dfx --exclude='.idea' $(mount | grep -oP '/var/www/magento2ce/\K\S*' | xargs -rn 1 echo '-e ')
   git checkout composer.lock composer.json
fi

for edition in "$@"
do
    cp -rlf ../magento2${edition}/!(.git|vendor|..|.) .
done

composer install

bin/magento setup:install \
   --cleanup-database \
   --backend-frontname=admin \
   --admin-lastname=Admin \
   --admin-firstname=Admin \
   --admin-email=magento@mailinator.com \
   --admin-user=admin \
   --admin-password=123123q \
   --db-name=magento \
   --db-host=db \
   --db-prefix=m2_

#setup other services
IFS=$'\n' setup=($(yq read /var/www/magento-docker/docker-compose.yml services.*.x-setup | grep -oP '(?:\-\s)+(?!null)\K.*'))
for i in ${setup[*]}; do eval ${i}; done

composer dump-autoload --optimize