#!/bin/bash
shopt -s extglob

#clean project dir
if [[ -d .git ]]; then
   git clean -dfx -e '.idea' $(mount | grep -oP '/var/www/magento2ce/\K\S*' | xargs -rn 1 echo '-e ')
   git checkout composer.json
fi

#apply edition
for edition in "$@"; do
   if ! [[ -d ../${edition} ]]; then
      edition=magento2${edition}
   fi
   if [[ -f ../${edition}/composer.json ]]; then
      git -C ../"${edition}" checkout composer.json
   fi
   cp -rlf ../"${edition}"/!(.git|vendor|..|.) .
done

#install magento
composer config minimum-stability dev
composer config repositories.composer '{"type": "composer", "url": "https://repo.magento.com/", "canonical": false}'
composer config repositories.path '{"type": "path","url": "../*/*", "canonical": false}'
composer config allow-plugins true
composer update
bin/magento setup:install -n \
   --cleanup-database \
   --backend-frontname=admin \
   --admin-lastname=Admin \
   --admin-firstname=Admin \
   --admin-email=magento@mailinator.com \
   --admin-user=admin \
   --admin-password=123123q \
   --db-name=magento \
   --db-host=db \
   --elasticsearch-host=elastic \
   --enable-modules=all \
   --key=magento_super_puper_secret_key32 \
   --allow-parallel-generation \
   --db-prefix=m2_

#do x-setup lines
IFS=$'\n' setup=($(yq eval .services.*.x-setup /var/www/magento-docker/docker-compose.yml | grep -oP '^(?:\s*\-\s)+(?!null)\K.*'))
for i in ${setup[*]}; do eval "${i}"; done
