version: '3.7'
services:
  app-search:
    image: mslabko/php-with-grpc
# to re-build image with gRPC use the following docker file:
    build:
      context: .
      dockerfile: build/php/fpm-grpc-search
    hostname: app-search
    ports:
      - "${SSH_PORT}:22"
    stop_signal: SIGKILL
    volumes:
      - ${MAGENTO_PATH}/magento-search:/var/www/magento-search:${FILE_SYNC}
      - ./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/magento-docker
      - ./etc/php/tools:/usr/local/bin/magento2:ro
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf

    environment:
      COMPOSER_HOME: /var/www/.composer
    command: sh -c 'service ssh start; php-fpm -R'
    x-hints:
    x-setup:
    x-info: https://devdocs.magento.com/
# Uncomment after gRPC server executed.
#  grpcui:
#    image: wongnai/grpcui
#    ports:
#      - "8080:8080"
#    volumes:
#      - code:/var/www
#    entrypoint: ["grpcui", "-plaintext", "-proto", "/var/www/magento-search/search.proto", "-port", "8080", "-bind", "0.0.0.0", "-import-path", "/var/www/magento-search", "app:9001"
networks:
  default:
    driver: bridge
